version: '1.0'

services:
    ngx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./repo:/repo
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - repo-network
    php:
        image: php:fpm
        ports:
        - 9000
        volumes:
            - ./repo:/repo
        networks:
            - repo-network

networks:
    repo-network:
        driver: bridge
